"""
Cogs package for Acosmibot.

This module defines which cogs are enabled for the bot.
To enable/disable a cog, add/remove it from the __all__ list below.
"""

__all__ = [
    "Admin_Start_Lotto",
    "ReminderCommand",
    "Bank",
    "Avatar",
    "Slots",
    "Blackjack",
    "Giphy",
    "Deathroll",
    "Dictionary",
    "Ping",
    "Help",
    "Nasa",
    "Weather",
    "Balance",
    "Rank",
    "Stats",
    "StatsGames",
    "Give",
    "Check_Bank",
    "Eightball",
    "Polymorph",
    "Coinflip",
    "Rock_Paper_Scissors",
    "Leaderboard",
    "Reset_RPS",
    "LevelingListener",
    "On_Message",
    "On_Reaction",
    "On_Member_Join",
    "On_Raw_Member_Remove",
    "On_Guild_Join",
    "AIControls",
    "PortalCommands",
    "PortalMessageListener",
    "ReactionRoles",
    # "ActivityDiagnostic",
    # "RipAudio",
    # "Burn",
    # "Reset_AI_Thread",
    # "Reset_Season",
    # "Reset_Daily",
    # "Roll_Dice",
    # "Bailout",
    # "Jail_Message",
    # "Admin_Give",
    # "Color",  # fix this soon
    # "RPG",
    # "Admin_Jail",
    # "Admin_Jail_Release",
    # "Admin_Stats",
    # "DeleteAiThread",
]
